require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNClassStructure' do
  config = use_native_modules!
  #permissions_path = '../node_modules/react-native-permissions/ios'
  use_react_native!(:path => config["reactNativePath"])
  target 'RNClassStructureTests' do
    inherit! :complete
    # Pods for testing
    # 
    #pod 'Permission-LocationAccuracy', :path => "../node_modules/react-native-permissions/ios/LocationAccuracy"
    #pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways"
    #pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse"
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNClassStructure-tvOS' do
  # Pods for RNClassStructure-tvOS

  target 'RNClassStructure-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
